---
apiVersion: batch/v1
kind: Job
metadata:
  name: learner
spec:
  parallelism: 4
  template:
    metadata:
      name: learner
    spec:
      containers:
        - name: learner
          image: chrisai/haiku-scalable-example-learner:test
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: actor
spec:
  template:
    spec:
      containers:
        - name: actor
          image: chrisai/haiku-scalable-example-actor:test
          env:
            - name: GRPC_HOST
              value: "localhost:50051"
      restartPolicy: OnFailure
