apiVersion: v1
kind: Pod
metadata:
  name: impala
spec:
  containers:
    - name: learner
      image: chrisai/haiku-scalable-example-learner:test
      ports:
        - containerPort: 50051
    - name: actor
      image: chrisai/haiku-scalable-example-actor:test