apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: learner
spec:
  selector:
    matchLabels:
      app: learner
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: learner
    spec:
      containers:
        - name: learner
          image: chrisai/haiku-scalable-example-learner:test
          ports:
            - containerPort: 50051