version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:

  build-and-test:
    docker:
      - image: chrisai/haiku-scalable-example-base:latest
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: PYTHONPATH=. python -m pytest --cov-config=.coveragerc --cov=.
          name: Test
      - run:
          command: PYTHONPATH=. python -m pylint --ignore=message_pb2.py,message_pb2_grpc.py *.py
          name: Lint
      - run:
          command: COVERALLS_REPO_TOKEN=uzR6LezWHZjXDf2LpaxMOBmFq2vcgmDmm python -m coveralls
          name: Coverage Submit
      - run:
          command: python -m coverage html
          name: Coverage
      - store_artifacts:
          path: htmlcov
          destination: coverage

workflows:
  main:
    jobs:
      - build-and-test
