version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:

  build-and-test:
    docker:
      - image: chrisai/haiku-scalable-example-base:test
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: PYTHONPATH=. python -m pytest --cov=.
          name: Test
      - run:
          command: python -m coverage html
          name: Coverage
      - run:
          command: python -m coveralls
          name: Coverage Submit
      - store_artifacts:
          path: htmlcov
          destination: coverage

workflows:
  main:
    jobs:
      - build-and-test
